//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


namespace openstig_read_api.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CHECKLIST {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASSET", typeof(CHECKLISTASSET), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("STIGS", typeof(CHECKLISTSTIGS), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CHECKLISTASSET {
        
        private string rOLEField;
        
        private string aSSET_TYPEField;
        
        private string hOST_NAMEField;
        
        private string hOST_IPField;
        
        private string hOST_MACField;
        
        private string hOST_FQDNField;
        
        private string tECH_AREAField;
        
        private string tARGET_KEYField;
        
        private string wEB_OR_DATABASEField;
        
        private string wEB_DB_SITEField;
        
        private string wEB_DB_INSTANCEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ROLE {
            get {
                return this.rOLEField;
            }
            set {
                this.rOLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ASSET_TYPE {
            get {
                return this.aSSET_TYPEField;
            }
            set {
                this.aSSET_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOST_NAME {
            get {
                return this.hOST_NAMEField;
            }
            set {
                this.hOST_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOST_IP {
            get {
                return this.hOST_IPField;
            }
            set {
                this.hOST_IPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOST_MAC {
            get {
                return this.hOST_MACField;
            }
            set {
                this.hOST_MACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOST_FQDN {
            get {
                return this.hOST_FQDNField;
            }
            set {
                this.hOST_FQDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TECH_AREA {
            get {
                return this.tECH_AREAField;
            }
            set {
                this.tECH_AREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARGET_KEY {
            get {
                return this.tARGET_KEYField;
            }
            set {
                this.tARGET_KEYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEB_OR_DATABASE {
            get {
                return this.wEB_OR_DATABASEField;
            }
            set {
                this.wEB_OR_DATABASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEB_DB_SITE {
            get {
                return this.wEB_DB_SITEField;
            }
            set {
                this.wEB_DB_SITEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WEB_DB_INSTANCE {
            get {
                return this.wEB_DB_INSTANCEField;
            }
            set {
                this.wEB_DB_INSTANCEField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CHECKLISTSTIGS {
        
        private CHECKLISTSTIGSISTIG[] iSTIGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("iSTIG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CHECKLISTSTIGSISTIG[] iSTIG {
            get {
                return this.iSTIGField;
            }
            set {
                this.iSTIGField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CHECKLISTSTIGSISTIG {
        
        private CHECKLISTSTIGSISTIGSTIG_INFOSI_DATA[][] sTIG_INFOField;
        
        private CHECKLISTSTIGSISTIGVULN[] vULNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SI_DATA", typeof(CHECKLISTSTIGSISTIGSTIG_INFOSI_DATA[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CHECKLISTSTIGSISTIGSTIG_INFOSI_DATA[][] STIG_INFO {
            get {
                return this.sTIG_INFOField;
            }
            set {
                this.sTIG_INFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VULN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CHECKLISTSTIGSISTIGVULN[] VULN {
            get {
                return this.vULNField;
            }
            set {
                this.vULNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CHECKLISTSTIGSISTIGSTIG_INFOSI_DATA {
        
        private string sID_NAMEField;
        
        private string sID_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SID_NAME {
            get {
                return this.sID_NAMEField;
            }
            set {
                this.sID_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SID_DATA {
            get {
                return this.sID_DATAField;
            }
            set {
                this.sID_DATAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CHECKLISTSTIGSISTIGVULN {
        
        private string sTATUSField;
        
        private string fINDING_DETAILSField;
        
        private string cOMMENTSField;
        
        private string sEVERITY_OVERRIDEField;
        
        private string sEVERITY_JUSTIFICATIONField;
        
        private CHECKLISTSTIGSISTIGVULNSTIG_DATA[] sTIG_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FINDING_DETAILS {
            get {
                return this.fINDING_DETAILSField;
            }
            set {
                this.fINDING_DETAILSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMMENTS {
            get {
                return this.cOMMENTSField;
            }
            set {
                this.cOMMENTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEVERITY_OVERRIDE {
            get {
                return this.sEVERITY_OVERRIDEField;
            }
            set {
                this.sEVERITY_OVERRIDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEVERITY_JUSTIFICATION {
            get {
                return this.sEVERITY_JUSTIFICATIONField;
            }
            set {
                this.sEVERITY_JUSTIFICATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("STIG_DATA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CHECKLISTSTIGSISTIGVULNSTIG_DATA[] STIG_DATA {
            get {
                return this.sTIG_DATAField;
            }
            set {
                this.sTIG_DATAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CHECKLISTSTIGSISTIGVULNSTIG_DATA {
        
        private string vULN_ATTRIBUTEField;
        
        private string aTTRIBUTE_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VULN_ATTRIBUTE {
            get {
                return this.vULN_ATTRIBUTEField;
            }
            set {
                this.vULN_ATTRIBUTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATTRIBUTE_DATA {
            get {
                return this.aTTRIBUTE_DATAField;
            }
            set {
                this.aTTRIBUTE_DATAField = value;
            }
        }
    }
} // end namespace